Repository AY2425S2-CS2103T-W09-2/tp, pull requests merged in 2025-04, with the labels that each got.

#129 Make request comparison case-insensitive
  src/main/java/seedu/guestnote/model/request/Request.java
Labels: alpha-bug

#121 Update UMl diagrams
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
Labels: alpha-bug

#128 Fix find comman not able to search name and phone number
  src/main/java/seedu/guestnote/model/guest/AnyFieldContainsKeywordsPredicate.java
  src/main/java/seedu/guestnote/model/guest/FieldContainsKeywordsPredicate.java
  src/test/java/seedu/guestnote/model/guest/FieldContainsKeywordsPredicateTest.java
Labels: alpha-bug

#135 Refactor address book to guest note for uml diagrams
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: priority.Low

#149 Fix indent-related issues in UG
  docs/UserGuide.md
  docs/package-lock.json
  docs/package.json
Labels: alpha-bug

#163 Refactor Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: priority.Medium

#153 Add list all guests with requests
  src/main/java/seedu/guestnote/logic/commands/ListCommand.java
  src/main/java/seedu/guestnote/logic/parser/ListCommandParser.java
  src/test/java/seedu/guestnote/logic/commands/ListCommandTest.java
Labels: priority.High

#140 Fix status UI display
  src/main/java/seedu/guestnote/ui/GuestCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/GuestListCard.fxml
  src/main/resources/view/LightTheme.css
Labels: alpha-bug

#162 Limit Request to 75 characters
  src/main/java/seedu/guestnote/model/request/Request.java
  src/main/java/seedu/guestnote/ui/GuestCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/test/java/seedu/guestnote/model/request/RequestTest.java
Labels: alpha-bug

#123 Add restrictions to Email length
  src/main/java/seedu/guestnote/model/guest/Email.java
  src/test/java/seedu/guestnote/model/guest/EmailTest.java
Labels: alpha-bug

#117 Add validation for Phone length
  src/main/java/seedu/guestnote/model/guest/Phone.java
  src/test/java/seedu/guestnote/model/guest/PhoneTest.java
Labels: alpha-bug

#148 Fix partial match for request field
  src/main/java/seedu/guestnote/model/guest/FieldContainsKeywordsPredicate.java
  src/test/java/seedu/guestnote/model/guest/FieldContainsKeywordsPredicateTest.java
Labels: alpha-bug

#175 Update find command and list command
  docs/UserGuide.md
Labels: priority.High, alpha-bug

#178 Change list rq to list rq/
  src/main/java/seedu/guestnote/logic/parser/ListCommandParser.java
Labels: alpha-bug

#181 Fix find and list command
  src/main/java/seedu/guestnote/logic/commands/ListCommand.java
  src/main/java/seedu/guestnote/logic/parser/FindCommandParser.java
  src/main/java/seedu/guestnote/logic/parser/ListCommandParser.java
  src/main/java/seedu/guestnote/model/guest/FieldContainsSubstringsPredicate.java
  src/main/java/seedu/guestnote/model/guest/MultiPredicate.java
  src/main/java/seedu/guestnote/model/guest/NameContainsSubstringsPredicate.java
  src/test/java/seedu/guestnote/logic/commands/CommandTestUtil.java
  src/test/java/seedu/guestnote/logic/commands/FindCommandTest.java
  src/test/java/seedu/guestnote/logic/commands/ListCommandTest.java
  src/test/java/seedu/guestnote/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/guestnote/logic/parser/GuestNoteParserTest.java
  src/test/java/seedu/guestnote/model/ModelManagerTest.java
  src/test/java/seedu/guestnote/model/guest/MultiPredicateTest.java
  src/test/java/seedu/guestnote/model/guest/NameContainsSubstringsPredicateTest.java
Labels: alpha-bug

#182 Merge fix def json
  src/test/data/JsonSerializableGuestNoteTest/typicalGuestsGuestNote.json
  src/test/java/seedu/guestnote/logic/commands/CommandTestUtil.java
  src/test/java/seedu/guestnote/logic/commands/EditCommandTest.java
  src/test/java/seedu/guestnote/logic/commands/EditGuestDescriptorTest.java
  src/test/java/seedu/guestnote/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/guestnote/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/guestnote/model/GuestNoteTest.java
  src/test/java/seedu/guestnote/model/guest/GuestTest.java
  src/test/java/seedu/guestnote/model/guest/UniqueGuestListTest.java
  src/test/java/seedu/guestnote/testutil/TypicalGuests.java
Labels: alpha-bug

#183 Merge duplicate add req error
  src/main/java/seedu/guestnote/logic/parser/AddCommandParser.java
  src/test/java/seedu/guestnote/logic/commands/CommandTestUtil.java
  src/test/java/seedu/guestnote/logic/commands/EditCommandTest.java
  src/test/java/seedu/guestnote/logic/commands/EditGuestDescriptorTest.java
  src/test/java/seedu/guestnote/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/guestnote/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/guestnote/model/GuestNoteTest.java
  src/test/java/seedu/guestnote/model/guest/GuestTest.java
  src/test/java/seedu/guestnote/model/guest/UniqueGuestListTest.java
  src/test/java/seedu/guestnote/testutil/TypicalGuests.java
Labels: alpha-bug

#254 Preserve Display View after EditCommand
  src/main/java/seedu/guestnote/logic/commands/EditCommand.java
  src/test/java/seedu/guestnote/logic/commands/EditCommandTest.java
Labels: alpha-bug

#255 Change error message to include proper format
  src/main/java/seedu/guestnote/model/guest/RoomNumber.java
Labels: alpha-bug

#256 Change Name Constraints
  src/main/java/seedu/guestnote/logic/parser/CliSyntax.java
  src/main/java/seedu/guestnote/model/guest/Name.java
  src/test/java/seedu/guestnote/logic/parser/ParserUtilTest.java
  src/test/java/seedu/guestnote/model/guest/NameTest.java
  src/test/java/seedu/guestnote/storage/JsonAdaptedGuestTest.java
Labels: alpha-bug
