Repository AY2425S2-CS2103T-W09-2/tp, pull requests merged in 2025-03, with the labels that each got.

#43 Update developer guide for user requirements
  docs/DeveloperGuide.md
Labels: type.Task

#51 Drop Field Address from Guest class
  docs/UserGuide.md
  src/main/java/seedu/guestnote/logic/Messages.java
  src/main/java/seedu/guestnote/logic/commands/AddCommand.java
  src/main/java/seedu/guestnote/logic/commands/EditCommand.java
  src/main/java/seedu/guestnote/logic/parser/AddCommandParser.java
  src/main/java/seedu/guestnote/logic/parser/CliSyntax.java
  src/main/java/seedu/guestnote/logic/parser/EditCommandParser.java
  src/main/java/seedu/guestnote/logic/parser/ParserUtil.java
  src/main/java/seedu/guestnote/model/guest/Address.java
  src/main/java/seedu/guestnote/model/guest/Guest.java
  src/main/java/seedu/guestnote/model/util/SampleDataUtil.java
  src/main/java/seedu/guestnote/storage/JsonAdaptedPerson.java
  src/main/java/seedu/guestnote/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonGuestBookStorageTest/invalidAndValidPersonGuestBook.json
  src/test/data/JsonGuestBookStorageTest/invalidPersonGuestBook.json
  src/test/data/JsonSerializableGuestBookTest/duplicatePersonGuestBook.json
  src/test/data/JsonSerializableGuestBookTest/invalidPersonGuestBook.json
  src/test/data/JsonSerializableGuestBookTest/typicalPersonsGuestBook.json
  src/test/java/seedu/guestnote/logic/LogicManagerTest.java
  src/test/java/seedu/guestnote/logic/commands/CommandTestUtil.java
  src/test/java/seedu/guestnote/logic/commands/EditGuestDescriptorTest.java
  src/test/java/seedu/guestnote/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/guestnote/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/guestnote/logic/parser/ParserUtilTest.java
  src/test/java/seedu/guestnote/model/GuestBookTest.java
  src/test/java/seedu/guestnote/model/guest/AddressTest.java
  src/test/java/seedu/guestnote/model/guest/GuestTest.java
  src/test/java/seedu/guestnote/model/guest/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/guestnote/model/guest/UniqueGuestListTest.java
  src/test/java/seedu/guestnote/storage/JsonAdaptedGuestTest.java
  src/test/java/seedu/guestnote/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/guestnote/testutil/PersonBuilder.java
  src/test/java/seedu/guestnote/testutil/PersonUtil.java
  src/test/java/seedu/guestnote/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#65 Modify unique guest constraints
  src/main/java/seedu/guestnote/model/guest/Guest.java
  src/main/java/seedu/guestnote/model/guest/StayDuration.java
  src/test/java/seedu/guestnote/model/guest/CheckInTest.java
  src/test/java/seedu/guestnote/model/guest/CheckOutTest.java
  src/test/java/seedu/guestnote/model/guest/GuestTest.java
  src/test/java/seedu/guestnote/model/guest/StayDurationTest.java
Labels: type.Task

#74 Change Request Set to Request List
  src/main/java/seedu/guestnote/logic/LogicManager.java
  src/main/java/seedu/guestnote/logic/commands/EditCommand.java
  src/main/java/seedu/guestnote/logic/parser/AddCommandParser.java
  src/main/java/seedu/guestnote/logic/parser/EditCommandParser.java
  src/main/java/seedu/guestnote/logic/parser/GuestBookParser.java
  src/main/java/seedu/guestnote/logic/parser/ParserUtil.java
  src/main/java/seedu/guestnote/model/guest/Guest.java
  src/main/java/seedu/guestnote/model/request/Request.java
  src/main/java/seedu/guestnote/model/request/UniqueRequestList.java
  src/main/java/seedu/guestnote/model/request/exceptions/DuplicateRequestException.java
  src/main/java/seedu/guestnote/model/request/exceptions/RequestNotFoundException.java
  src/main/java/seedu/guestnote/model/util/SampleDataUtil.java
  src/main/java/seedu/guestnote/storage/JsonAdaptedPerson.java
  src/main/java/seedu/guestnote/ui/PersonCard.java
  src/test/java/seedu/guestnote/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/guestnote/logic/parser/GuestBookParserTest.java
  src/test/java/seedu/guestnote/logic/parser/ParserUtilTest.java
  src/test/java/seedu/guestnote/model/request/RequestTest.java
  src/test/java/seedu/guestnote/model/request/UniqueRequestListTest.java
  src/test/java/seedu/guestnote/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/guestnote/testutil/PersonBuilder.java
  src/test/java/seedu/guestnote/testutil/PersonUtil.java
  src/test/java/seedu/guestnote/testutil/TypicalRequests.java
Labels: type.Story, priority.Medium

#78 Drop all tag and replace with request
  docs/UserGuide.md
  src/main/java/seedu/guestnote/logic/Messages.java
  src/main/java/seedu/guestnote/logic/commands/AddCommand.java
  src/main/java/seedu/guestnote/logic/commands/EditCommand.java
  src/main/java/seedu/guestnote/logic/parser/AddCommandParser.java
  src/main/java/seedu/guestnote/logic/parser/CliSyntax.java
  src/main/java/seedu/guestnote/logic/parser/EditCommandParser.java
  src/main/java/seedu/guestnote/logic/parser/ParserUtil.java
  src/main/java/seedu/guestnote/model/request/Request.java
  src/main/java/seedu/guestnote/storage/JsonAdaptedPerson.java
  src/main/java/seedu/guestnote/storage/JsonAdaptedRequest.java
  src/main/java/seedu/guestnote/ui/PersonCard.java
  src/test/data/JsonSerializableGuestBookTest/duplicatePersonGuestBook.json
  src/test/data/JsonSerializableGuestBookTest/typicalPersonsGuestBook.json
  src/test/java/seedu/guestnote/logic/commands/CommandTestUtil.java
  src/test/java/seedu/guestnote/logic/commands/EditCommandTest.java
  src/test/java/seedu/guestnote/logic/commands/EditGuestDescriptorTest.java
  src/test/java/seedu/guestnote/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/guestnote/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/guestnote/logic/parser/ParserUtilTest.java
  src/test/java/seedu/guestnote/model/GuestBookTest.java
  src/test/java/seedu/guestnote/model/guest/GuestTest.java
  src/test/java/seedu/guestnote/model/guest/UniqueGuestListTest.java
  src/test/java/seedu/guestnote/model/request/RequestTest.java
  src/test/java/seedu/guestnote/storage/JsonAdaptedGuestTest.java
  src/test/java/seedu/guestnote/testutil/PersonBuilder.java
  src/test/java/seedu/guestnote/testutil/PersonUtil.java
  src/test/java/seedu/guestnote/testutil/TypicalPersons.java
Labels: type.Task

#88 Add check-in / check-out commands and status field to Guest
  src/main/java/seedu/guestnote/logic/commands/CheckInCommand.java
  src/main/java/seedu/guestnote/logic/commands/CheckOutCommand.java
  src/main/java/seedu/guestnote/logic/commands/EditCommand.java
  src/main/java/seedu/guestnote/logic/parser/AddCommandParser.java
  src/main/java/seedu/guestnote/logic/parser/CheckInCommandParser.java
  src/main/java/seedu/guestnote/logic/parser/CheckOutCommandParser.java
  src/main/java/seedu/guestnote/logic/parser/GuestBookParser.java
  src/main/java/seedu/guestnote/model/guest/Guest.java
  src/main/java/seedu/guestnote/model/guest/Status.java
  src/main/java/seedu/guestnote/model/util/SampleDataUtil.java
  src/main/java/seedu/guestnote/storage/JsonAdaptedPerson.java
  src/main/java/seedu/guestnote/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonGuestBookStorageTest/invalidAndValidPersonGuestBook.json
  src/test/data/JsonGuestBookStorageTest/invalidPersonGuestBook.json
  src/test/data/JsonSerializableGuestBookTest/duplicatePersonGuestBook.json
  src/test/data/JsonSerializableGuestBookTest/invalidPersonGuestBook.json
  src/test/data/JsonSerializableGuestBookTest/typicalPersonsGuestBook.json
  src/test/java/seedu/guestnote/logic/commands/CheckInCommandTest.java
  src/test/java/seedu/guestnote/logic/commands/CheckOutCommandTest.java
  src/test/java/seedu/guestnote/logic/commands/CommandTestUtil.java
  src/test/java/seedu/guestnote/logic/parser/CheckInCommandParserTest.java
  src/test/java/seedu/guestnote/logic/parser/CheckOutCommandParserTest.java
  src/test/java/seedu/guestnote/logic/parser/GuestBookParserTest.java
  src/test/java/seedu/guestnote/model/guest/GuestTest.java
  src/test/java/seedu/guestnote/model/guest/StatusTest.java
  src/test/java/seedu/guestnote/storage/JsonAdaptedGuestTest.java
  src/test/java/seedu/guestnote/testutil/PersonBuilder.java
  src/test/java/seedu/guestnote/testutil/TypicalPersons.java
Labels: priority.Medium

#91 Update UG
  docs/UserGuide.md
Labels: priority.High

#79 Add -ri/ Prefix Parsing for Request Index Deletion in EditCommand
  src/main/java/seedu/guestnote/logic/commands/EditCommand.java
  src/main/java/seedu/guestnote/logic/parser/AddCommandParser.java
  src/main/java/seedu/guestnote/logic/parser/CliSyntax.java
  src/main/java/seedu/guestnote/logic/parser/EditCommandParser.java
  src/main/java/seedu/guestnote/logic/parser/ParserUtil.java
  src/main/java/seedu/guestnote/model/request/UniqueRequestList.java
  src/main/java/seedu/guestnote/model/request/exceptions/DuplicateRequestException.java
  src/main/java/seedu/guestnote/model/request/exceptions/RequestException.java
  src/main/java/seedu/guestnote/model/request/exceptions/RequestNotFoundException.java
  src/test/java/seedu/guestnote/logic/commands/CommandTestUtil.java
  src/test/java/seedu/guestnote/logic/commands/EditCommandTest.java
  src/test/java/seedu/guestnote/logic/commands/EditGuestDescriptorTest.java
  src/test/java/seedu/guestnote/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/guestnote/logic/parser/ParserUtilTest.java
  src/test/java/seedu/guestnote/testutil/EditGuestDescriptorBuilder.java
  src/test/java/seedu/guestnote/testutil/GuestUtil.java
Labels: type.Story, type.Enhancement, priority.Medium

#113 Fix original testcase with name starting with empty spaces
  src/test/java/seedu/guestnote/model/guest/FieldContainsKeywordsPredicateTest.java
Labels: alpha-bug

#112 Refactor check-in and check-out classes to inherit from abstract class
  src/main/java/seedu/guestnote/logic/commands/CheckInCommand.java
  src/main/java/seedu/guestnote/logic/commands/CheckOutCommand.java
  src/main/java/seedu/guestnote/logic/commands/StatusChangeCommand.java
Labels: severity.Low, priority.Low
